language: node_js
node_js:
  - '10'
  - '8'
  - '6'
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install --ignore-engines
script:
  - yarn commitlint-travis
  - yarn lint
  - yarn build
  - yarn test --verbose
after_script:
  - yarn codecov
